name: pipeline
on: workflow_dispatch
jobs:
    compilation:
        runs-on: ubuntu-lastest
        env:
            USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            PASSWORD: ${{ secrets.DOCKERHUB.PASSWORD }}
            REPO_NAME: ${{ github.repository.name }}
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: intall JDK
              uses: actions/setup-java@4
              with:
                distribution: 'oracle'
                java-version: '21'
            - name: get maven dependecies 
              run: mvn dependency:resolve
            - name: Cache local Maven repository
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
            - name: get .jar
              run: mvn clean package
            - name: upload artifact
              if: success() && github.ref == 'refs/heads/main'
              uses: actions/upload-artifact@v4
              with:
                name: $REPO_NAME
                path: target/*.jar
            - name: get release GithGub
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ github.ref_name }}
                name: Release ${{ github.ref }}
                files: target/*.jar
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Docker Image
              run: docker build -t $USERNAME/$REPO_NAME .
            - name: push dockerhub
              run: docker push $USERNAME/$REPO_NAME
              
            
            
            
            
